# NumPy Introduction

- NumPy is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks
- NumPy is also incredibly fast, as it has bindings to C libraries

In [1]:
import numpy as np

# NumPy Arrays

- Vectors (1D arrays) or Matrices (2D arrays)

## Creating NumPy Arrays

### From a Python List
We can create an array by directly converting a list or list of lists:

In [2]:
my_list=[1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods
There are lots of built in ways to generate arrays

#### arange
Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### zeros and ones
Generate arrays of zeros or ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace
Return evenly spaced numbers over a specified interval.

In [11]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0,10,49)

array([ 0.        ,  0.20833333,  0.41666667,  0.625     ,  0.83333333,
        1.04166667,  1.25      ,  1.45833333,  1.66666667,  1.875     ,
        2.08333333,  2.29166667,  2.5       ,  2.70833333,  2.91666667,
        3.125     ,  3.33333333,  3.54166667,  3.75      ,  3.95833333,
        4.16666667,  4.375     ,  4.58333333,  4.79166667,  5.        ,
        5.20833333,  5.41666667,  5.625     ,  5.83333333,  6.04166667,
        6.25      ,  6.45833333,  6.66666667,  6.875     ,  7.08333333,
        7.29166667,  7.5       ,  7.70833333,  7.91666667,  8.125     ,
        8.33333333,  8.54166667,  8.75      ,  8.95833333,  9.16666667,
        9.375     ,  9.58333333,  9.79166667, 10.        ])

#### eye
Creates an Identity Matrix

In [13]:
np.eye(4,dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#### Random
- NumPy also has a lot of ways to create random number arrays:

##### rand
Creates an array of the given shape and populate it with random samples from a uniform distribution  over [0,1)

In [14]:
np.random.rand(2)

array([0.14395006, 0.11879953])

In [15]:
np.random.rand(5,5)

array([[0.59436598, 0.59705599, 0.15841752, 0.33554586, 0.46300561],
       [0.83921546, 0.39946213, 0.83256   , 0.09929972, 0.1927226 ],
       [0.73288165, 0.53556982, 0.6599671 , 0.23077558, 0.59814063],
       [0.38357906, 0.72108909, 0.44022134, 0.41840215, 0.53100475],
       [0.26238949, 0.29583778, 0.68019574, 0.57813164, 0.6390862 ]])

##### randn 
Return a sample from the standard normal distribution. Unlike rand which is uniform:

In [16]:
np.random.randn(5,5)

array([[-0.2876113 ,  0.89627189, -1.27705519,  1.53904233,  1.14086528],
       [ 0.10896702,  0.71123566, -0.39750532, -2.03738383,  0.14418323],
       [-0.32979527, -0.03132465,  0.27023985, -0.92170729,  1.2994241 ],
       [ 0.95514412,  0.38825877, -0.67394146, -1.14695528,  0.05947914],
       [ 0.20330091, -1.1119132 ,  0.32519009,  0.46068431,  1.02501263]])

##### randint
Return random numbers in [a,b)

In [17]:
np.random.randint(1,10,20)

array([7, 5, 8, 4, 8, 3, 3, 2, 5, 2, 5, 9, 9, 3, 8, 4, 7, 2, 4, 5])

## Array Attributes and Methods

In [18]:
arr = np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr = np.random.randint(0,50,10)

In [21]:
ranarr

array([43,  9, 49,  4,  3, 16, 26, 19,  1,  1])

### Reshape
Returns an array containing the same data with a new shape.

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin
Methods for finding max or min values. 
Find their index location using argmin or argmax

In [23]:
x = np.zeros((10,10),"int")
x[:5,:5]
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr.max()

49

In [25]:
ranarr.argmax()

2

In [26]:
ranarr[ranarr.argmax()]

49

### Shape
Shape is an attribute that arrays have (not a method):

In [27]:
# Vector
arr.shape

(25,)

In [28]:
# Matrix
arr.reshape(5,5).shape

(5, 5)

In [29]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Grab the data type of the object in the array:

In [30]:
arr.dtype

dtype('int64')

# Testing an example

In [31]:
x = np.zeros((10,10),"int")
x[:5,:5]=arr.reshape(5,5)
print(x)

[[ 0  1  2  3  4  0  0  0  0  0]
 [ 5  6  7  8  9  0  0  0  0  0]
 [10 11 12 13 14  0  0  0  0  0]
 [15 16 17 18 19  0  0  0  0  0]
 [20 21 22 23 24  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
