# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection

In [4]:
# Get a value at an index
arr[8]

8

In [5]:
arr[-5:]

array([ 6,  7,  8,  9, 10])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

## Broadcasting
- NumPy arrays differ from a normal Python list because of their ability to broadcast
- A slice of an array is not a copy, it's a view of the original array. (To avoid memory problems)
- To copy an array, you need to be explicit

In [7]:
# Setting a value with an index range (Broadcasting)
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
lst = [0,1,2]

In [9]:
# First difference is you can assign one element
# to several index positions, as opposed to a list:
lst[:2] = [5,5]
# lst[:2] = 32 -> TypeError: can only assign an iterable
lst

[5, 5, 2]

In [10]:
# Reset the array
arr = np.arange(0,11)

In [11]:
# Slices
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
# Alter slice
slice_of_arr[:]=50
slice_of_arr += 25
slice_of_arr

array([75, 75, 75, 75, 75, 75])

In [13]:
# The changes alter the original array too!
arr

array([75, 75, 75, 75, 75, 75,  6,  7,  8,  9, 10])

In [14]:
# To get a copy, you need to be explicit
arr_copy = arr.copy()
arr_copy += 10
print(arr)
print(arr_copy)

[75 75 75 75 75 75  6  7  8  9 10]
[85 85 85 85 85 85 16 17 18 19 20]


## Indexing a matrix (2D array)
As expected: matrix[i,j] or matrix [row,col]

In [15]:
matrix = np.arange(5,50,5).reshape(3,3)
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
# Index row
matrix[1]

array([20, 25, 30])

In [17]:
# Index column
matrix[:,0]

array([ 5, 20, 35])

In [18]:
# Individual element
matrix[1,1]

25

In [19]:
matrix[1][1]

25

In [20]:
# 2D array slicing
# Get 2x2 matrix from top right corner
matrix[:2,1:]

array([[10, 15],
       [25, 30]])

## Fancy Indexing
- Allows you to select entire rows or columns out of order

In [21]:
matrix[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [22]:
# Fancy indexing can choose rows in any order
matrix[[1,0,2,0,0,0]]

array([[20, 25, 30],
       [ 5, 10, 15],
       [35, 40, 45],
       [ 5, 10, 15],
       [ 5, 10, 15],
       [ 5, 10, 15]])

In [23]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
# Can do the same for columns
matrix[:,[1,0,0,0,0,2,1]]

array([[10,  5,  5,  5,  5, 15, 10],
       [25, 20, 20, 20, 20, 30, 25],
       [40, 35, 35, 35, 35, 45, 40]])

## Selection
- Select elements based off of comparison operators

In [25]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [27]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
matrix[matrix>17]

array([20, 25, 30, 35, 40, 45])

In [29]:
matrix > 17

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [30]:
matrix[matrix > 17] = 99

In [31]:
matrix

array([[ 5, 10, 15],
       [99, 99, 99],
       [99, 99, 99]])